### ISSUE TITLE
Deobfuscated code

### ISSUE THREAD

**Issue by blha303** [coolguruji/youtube-to-mp3-converter-php-script#1]
For anyone else wondering, the obfuscated code turns out to be:

```php
$ytresponse = @file_get_contents("https://www.youtube.com/oembed?url=http%3A//youtube.com/watch%3Fv%3D$id&format=json");
$ytinfo = array();
$ytinfo = json_decode($ytresponse, true);
$type = $ytinfo['type'];
```

No reason for that to be encoded 15 times. https://www.unphp.net/decode/4edffe4d7c34bbbbb7460eadec830bd7/

**Comment by Obliterous** [comment]
Yeah, this is pretty spamtastic.

**Comment by owenvoke** [comment]
_sigh_ Nice. I wish I'd seen this issue/site before manually decoding it 🤦‍♂️
