### ISSUE TITLE
Remove string obfuscation to increase credibility

### ISSUE THREAD

**Issue by dusekdan** [coolguruji/youtube-to-mp3-converter-php-script#5]
Hello!

I understand that you feel like you want to protect the code which you probably researched and put a lot of effort into, but I would also like to point out that obfuscation is not the way.

First of all, obfuscating the payload this way will not prevent anyone from actually reading the code (#3 is and example of that). 

Construction containing `eval(chain_of_obfuscation_methods(obfuscated_string))` will however discourage a lot of security-aware people from using your application, as they won't be able to read the code easily before running it. 

More persistent people will then go and de-obfuscate your code to check it is not malicious code and they will discover your secret anyways.

Removing the eval + obfuscation part will result in:

* more people actually using your application,
* less people actually caring about how it is implemented.

Also, you decided to open-source your solution, so you know... why obfuscate the code now? So, what do you think?

**Comment by iekuzmuk** [comment]
$ytresponse = @file_get_contents("https://www.youtube.com/oembed?url=http%3A//youtube.com/watch%3Fv%3D$id&format=json"); 
$ytinfo = array(); 
$ytinfo = json_decode($ytresponse,true);
$type = $ytinfo['type'];


thats de code, i guess he is a genious of coding protecting his master pieace
even dow, the code is bullshit, it sends you to that page.. 

all blah blah to ends going to a page

**Comment by dusekdan** [comment]
Yes, I got through the process of de-obfuscating it too and figured that much. I will close this issue, there is no hope or reason to keep this open.

**Comment by E-B3rry** [comment]
No, he is not dumb, this is a prevention...
http://www.attila-php.net or try to search for "watch%3Fv%3D$id&format=json"

**Comment by dusekdan** [comment]
@Julot135 Feel free to elaborate on that prevention part... as far as I am concerned, it does not prevent anyone from anything.
